#!/bin/sh -eu

for i in '' 'bg' 'circle'; do
	for n in 16 24 32 48 64 128 256 512 1024 2048 4096; do
		printf "Exporting icon$i$n.png."

		${INKSCAPE:-inkscape} -w $n -h $n "public/icon$i.svg" \
		                      -o "public/icon$i$n.png"

		printf "\r\033[KExported icon$i$n.png.\n"
	done
done
