#!/bin/sh -eu

if [ $# -lt 3 ]; then
	echo "$0 host md [discussemail]" >&2
	exit 1
fi

host="$1"
md="$2"
discussemail="${3:-}"

if [ -n "$discussemail" ]; then
	pubdatets=$(head -n 1 "$md.time")
	pubdate=$(date -u -d @"$pubdatets" +"%Y-%m-%d")

	echo -n '<div id="publication-date">'
	echo -n '<span>'
	echo -n "Published on $pubdate"
	echo -n '</span>'
	echo -n '</div>'
fi

${LOWDOWN:-lowdown} -t html "$md" | sed "s|@HOST@|$host|g"

if [ -n "$discussemail" ]; then
	echo -n '<div id="discuss">'
	echo -n '<a class="glow-hover" href="mailto:'
	echo -n "$discussemail?subject=[Discuss]%20"
	echo -n "$(sed 's/ /%20/g' ${md%.md}.title)"
	echo -n '">Discuss</a>'
	echo -n '</div>'
fi
